/**
 * Builds app/tokens.generated.css from tokens/*.json.
 *
 * tokens/*.json mirror the Figma variable collections 1:1:
 *   primitives.json   -> Figma "Primitives" collection (single mode)
 *   theme.light.json  -> Figma "Theme" collection, "Light" mode
 *   theme.dark.json   -> Figma "Theme" collection, "Dark" mode  (delta only)
 *
 * Output:
 *   :root                        <- primitives + Light theme
 *   :root[data-theme="dark"]     <- Dark theme delta
 *
 * The token JSON is the source of truth; regenerate whenever it changes:
 *   npm run tokens   (also runs automatically via predev / prebuild)
 *
 * Colour values are already valid CSS (hex, 8-digit hex, var(--…), or a
 * {brand.*} reference), so we deliberately skip Style Dictionary's colour
 * transforms and only kebab-case the names.
 */
import { rm, mkdir, readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import StyleDictionary from "style-dictionary";

const ROOT = process.cwd();
const TMP = join(ROOT, ".tokens-build");
const OUT = join(ROOT, "app", "tokens.generated.css");

const commonFileOpts = {
  showFileHeader: false,
  outputReferences: true,
  commentStyle: "long",
  commentPosition: "inline",
};

function config(destination, selector, source, filter, log) {
  return {
    source,
    log,
    platforms: {
      css: {
        transforms: ["attribute/cti", "name/kebab"],
        buildPath: `${TMP}/`,
        files: [{ destination, format: "css/variables", filter, options: { ...commonFileOpts, selector } }],
      },
    },
  };
}

const themeOnly = (token) => token.filePath.endsWith("theme.dark.json");

const builds = [
  config("root.css", ":root", ["tokens/primitives.json", "tokens/theme.light.json"]),
  // The dark build includes primitives so {brand.*} references resolve, then
  // filters them back out of the output (they already live in :root). That
  // filtering trips a harmless "filtered out token references" warning, so
  // warnings are muted for this build only.
  config(
    "dark.css",
    ':root[data-theme="dark"]',
    ["tokens/primitives.json", "tokens/theme.dark.json"],
    themeOnly,
    { warnings: "disabled" },
  ),
];

await rm(TMP, { recursive: true, force: true });
await mkdir(TMP, { recursive: true });

for (const cfg of builds) {
  const sd = new StyleDictionary(cfg);
  await sd.buildAllPlatforms();
}

const header = `/* ============================================================
   AUTO-GENERATED by scripts/build-tokens.mjs — DO NOT EDIT.
   Source: tokens/*.json (mirrors the Figma "Primitives" and
   "Theme" variable collections). Run \`npm run tokens\` to rebuild.
   ============================================================ */

`;

const tidy = (s) => s.trim().replaceAll("/** ", "/* ");
const root = tidy(await readFile(join(TMP, "root.css"), "utf8"));
const dark = tidy(await readFile(join(TMP, "dark.css"), "utf8"));

await writeFile(OUT, `${header}${root}\n\n${dark}\n`);
await rm(TMP, { recursive: true, force: true });

console.log(`✓ wrote ${OUT.replace(`${ROOT}/`, "")}`);
